trigger:
  branches:
    include:
      - main

variables:
  ACR_NAME: 'frontendrn' # Azure Container Registry
  RESOURCE_GROUP: 'frontend-RG'
  BACKEND_IMAGE_NAME: 'backend-image'
  FRONTEND_IMAGE_NAME: 'frontend-image'
  IMAGE_TAG: 'latest'

stages:
  - stage: Build
    displayName: 'Build and Push Docker Images'
    jobs:
      - job: Build
        displayName: 'Build and Push'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-connection' # Service Connection
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az acr login --name $(ACR_NAME)                
                # Create image for backend and push!
                docker build -t $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE_NAME):$(IMAGE_TAG) ./packages/backend
                docker push $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE_NAME):$(IMAGE_TAG)                
                # Create image for backend and push!
                docker build -t $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE_NAME):$(IMAGE_TAG) ./packages/frontend
                docker push $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE_NAME):$(IMAGE_TAG)
  
  - stage: Deploy
    displayName: 'Deploy to Azure Container Apps'
    dependsOn: Build
    jobs:
      - job: Deploy
        displayName: 'Deploy'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: AzureCLI@2
            inputs:
              azureSubscription: 'azure-connection' # Service Connection
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                # Update Backend Container App
                az containerapp update --name backend-container-app \
                  --resource-group $(RESOURCE_GROUP) \
                  --image $(ACR_NAME).azurecr.io/$(BACKEND_IMAGE_NAME):$(IMAGE_TAG)
                
                # Update Frontend Container App
                az containerapp update --name frontend-container-app \
                  --resource-group $(RESOURCE_GROUP) \
                  --image $(ACR_NAME).azurecr.io/$(FRONTEND_IMAGE_NAME):$(IMAGE_TAG)
