'use client';
import { useState } from 'react';
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Provider } from 'react-redux';
import { store } from '../app/store';
import "./globals.css";
import SideNav from "./sidenav";
import { Bars3Icon } from '@heroicons/react/24/outline';
import { useEffect } from 'react';
import { setUser } from '../features/auth/userSlice';


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    const [isSidebarVisible, setIsSidebarVisible] = useState(true);

    const toggleSidebar = () => {
        setIsSidebarVisible(!isSidebarVisible);
    };

    useEffect(() => {
      if (typeof window !== 'undefined') {
        const user = localStorage.getItem('user');
        if (user) {
          store.dispatch(setUser(JSON.parse(user)));
        }
      }
    }, []);

  return (
    <html lang="en">
      <body className={inter.className}>
      <Provider store={store}>
        <div className="flex h-screen flex-col md:flex-row md:overflow-hidden">
          <button 
            onClick={toggleSidebar} 
            className="fixed right-5 top-5 z-50 p-2 bg-blue-600 text-white rounded-md md:hidden"
          >
            <Bars3Icon className="h-6 w-6" />
          </button>
          {/* <div className="w-full h-full flex-none md:w-64 md:h-screen"> */}
          <div 
            className={`w-full md:w-64 ${isSidebarVisible ? 'block' : 'hidden'} md:block`}
          >
              <SideNav />
          </div>
          <div className="flex-grow p-6 md: overflow-y-auto md:p-12">{children}</div>
        </div>
      </Provider>
      </body>
    </html>
  );
}